# Generated by Django 3.2.7 on 2022-02-19 06:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locked_models', '0006_alter_editingnow_is_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditingNow',
            new_name='LockedModel',
        ),
    ]
