# Generated by Django 3.2.7 on 2021-09-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing_now', '0002_editingnow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editingnow',
            name='model_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
