# Generated by Django 3.2.7 on 2021-09-28 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing_now', '0003_alter_editingnow_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editingnow',
            name='is_updated',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
