# Generated by Django 3.2.7 on 2021-09-28 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('editing_now', '0004_alter_editingnow_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editingnow',
            name='is_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 12, 51, 48, 886998, tzinfo=utc)),
        ),
    ]
